name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente de deploy'
        required: true
        default: 'lab'
        type: choice
        options: [lab, develop]

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  ECR_REPOSITORY: fiap-mecanica-workshop-service
  K8S_DEPLOYMENT: workshop-service
  K8S_NAMESPACE: mecanica-ms

jobs:
  build-push:
    name: Build e Push ECR
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.push.outputs.image-uri }}

    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e Push
        id: push
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          SHA_TAG:  ${{ github.sha }}
        run: |
          IMAGE_URI=$REGISTRY/${{ env.ECR_REPOSITORY }}:$SHA_TAG
          docker build \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -t $IMAGE_URI \
            -t $REGISTRY/${{ env.ECR_REPOSITORY }}:latest .
          docker push $IMAGE_URI
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          echo "image-uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy K8s
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ inputs.environment }}-fiap-cluster

      - name: Atualizar imagem
        run: |
          kubectl set image deployment/${{ env.K8S_DEPLOYMENT }} \
            ${{ env.K8S_DEPLOYMENT }}=${{ needs.build-push.outputs.image-uri }} \
            -n ${{ env.K8S_NAMESPACE }}

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --timeout=3m
