name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente de deploy'
        required: true
        default: 'lab'
        type: choice
        options: [lab, develop]
      ecr_repository:
        description: 'Repositório ECR do serviço'
        required: true
        type: string
        default: 'fiap-mecanica-workshop-service'
      k8s_deployment:
        description: 'Nome do Deployment no k8s'
        required: true
        type: string
        default: 'workshop-service'

jobs:
  build:
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/build.yml@main
    with:
      ecr_repository: ${{ inputs.ecr_repository }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  deploy:
    needs: [build]
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
      k8s_deployment: ${{ inputs.k8s_deployment }}
      image_uri: ${{ needs.build.outputs.image-uri }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
