name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/test.yml@main
    with:
      service-name: workshop-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
